# Generated by Django 5.0.2 on 2026-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rooms', models.IntegerField()),
                ('tenants', models.IntegerField()),
                ('rent', models.IntegerField()),
            ],
        ),
    ]
