# Generated by Django 5.0.2 on 2026-03-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='tenants',
            field=models.IntegerField(default=0),
        ),
    ]
