# Generated by Django 5.0.2 on 2026-03-08 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Password must start with 6,7,8,9 and contain exactly 10 digits.', regex='^[6-9][0-9]{9}$')])),
            ],
        ),
    ]
