# Generated by Django 5.0.2 on 2026-03-12 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='guardian_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Password must start with 6,7,8,9 and contain exactly 10 digits.', regex='^[6-9][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='password',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Password must start with 6,7,8,9 and contain exactly 10 digits.', regex='^[6-9][0-9]{9}$')]),
        ),
    ]
