# Generated by Django 5.0.2 on 2026-03-15 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registeredusers_age_registeredusers_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredusers',
            name='password',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Password must start with 6,7,8,9 and contain exactly 10 digits.', regex='^[6-9][0-9]{9}$')]),
        ),
    ]
