# Generated by Django 5.0.2 on 2026-03-15 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registeredusers_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='guardian_number',
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='phone_number',
            field=models.CharField(default='NA', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Password must start with 6,7,8,9 and contain exactly 10 digits.', regex='^[6-9][0-9]{9}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Password must start with 6,7,8,9 and contain exactly 10 digits.', regex='^[6-9][0-9]{9}$')]),
        ),
    ]
