# Generated by Django 5.0.2 on 2026-03-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_registeredusers_guardian_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredusers',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
