# Generated by Django 5.0.2 on 2026-03-16 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_registeredusers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredusers',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Password must contain 1 uppercase, 1 lowercase, 1 number, 1 special character and be 8-16 characters long.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&#])[A-Za-z\\d@$!%*?&#]{8,16}$')]),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 6,7,8,9 and contain exactly 10 digits.', regex='^[6-9][0-9]{9}$')]),
        ),
    ]
